// <auto-generated />
namespace OnlineUserToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class linkstatuswithtodos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkstatuswithtodos));
        
        string IMigrationMetadata.Id
        {
            get { return "202011041956088_link-status-with-todos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
